version: 2
commands:
  sayhello:
    description: "A very simple command for demonstration purposes"
    parameters:
      to:
        type: string
        default: "Hello World"
    steps:
      - run: echo << parameters.to >>

jobs:
  build:
    docker:
      # Primary container image where all steps run.
      - image: buildpack-deps:trusty
      # Secondary container image on common network.
      - image: mongo:2.6.8
        command: [mongod, --smallfiles]

    working_directory: ~/

    steps:
      # command will execute in trusty container
      # and can access mongo on localhost
      - run: sleep 5 && nc -vz localhost 27017

#jobs:
#  job1:
#    docker:
#      - image: circleci/node:10
#
#    steps:
#      - checkout
#      - run: npm install
#      - run: npm test
#
#  job2:
#    docker:
#      - image: circleci/node:10
#
#    steps:
#      - checkout
#      - run: cat README.md

#workflows:
#  version: 2
#  one-and-two:
#    jobs

#  two-and-three:
#    jobs:
#      - job1
#      - job2:
#          requires:
#            - job1