version: 2
commands:
  sayhello:
    description: "A very simple command for demonstration purposes"
    parameters:
      to:
        type: string
        default: "Hello World"
    steps:
      - run: echo << parameters.to >>

jobs:
  build:
    docker:
      - image: buildpack-deps:trusty # primary container
        environment:
          ENV: CI

      - image: mongo:2.6.8
        command: [--smallfiles]

      - image: postgres:9.4.1
        environment:
          POSTGRES_USER: root

      - image: redis@sha256:54057dd7e125ca41afe526a877e8bd35ec2cdd33b9217e022ed37bdcf7d09673

#jobs:
#  job1:
#    docker:
#      - image: circleci/node:10
#
#    steps:
#      - checkout
#      - run: npm install
#      - run: npm test
#
#  job2:
#    docker:
#      - image: circleci/node:10
#
#    steps:
#      - checkout
#      - run: cat README.md

#workflows:
#  version: 2
#  one-and-two:
#    jobs

#  two-and-three:
#    jobs:
#      - job1
#      - job2:
#          requires:
#            - job1