version: 2.1
commands:
  sayhello:
    description: "A very simple command for demonstration purposes"
    parameters:
      to:
        type: string
        default: "Hello World"
    steps:
      - run: echo << parameters.to >>

executors:
  my-executor:
    docker:
      - image: circleci/ruby:2.5.1-node-browsers

jobs:
  job1:
    docker:
      - image: circleci/node:10

    steps:
      - checkout
      - run: npm install
      - run: npm test

  job2:
    docker:
      - image: circleci/node:10

    steps:
      - checkout
      - run: cat README.md

  my-job:
    executor: my-executor
    steps:
      - run: echo outside the executor

  test-job:
    docker:
      - image: buildpack-deps:trusty
          # Secondary container image on common network.
      - entrypoint: ["echo", "this is", "test"]
#      - image: mongo:2.6.8
#        command: [mongod, --smallfiles]
    working_directory: ~/
    steps:
            # command will execute in trusty container
            # and can access mongo on localhost
      - run: echo this is step

workflows:
  version: 2
  one-and-two:
    jobs:
      - test-job

#  two-and-three:
#    jobs:
#      - job1
#      - job2:
#          requires:
#            - job1